server:
  port:8082

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

test:
  message: Hello from inventory!!!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
