server:
  port:8083

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


test:
  message: this is from order


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
